server:
  port: 9001
  #graceful shutdown
  shutdown: graceful
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: backend
  lifecycle:
    #grace period 15?
    timeout-per-shutdown-phase: 15s
  datasource:
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
      idle-timeout: 600000
      max-lifetime: 1800000
  jwt:
    secret: ${JWT_SECRET}
  jpa:
    hibernate:
      ddl-auto: create
AWS:
  ACCESS:
    KEY:
      ID: ${AWS_ACCESS_KEY}
  SECRET:
    ACCESS:
      KEY: ${AWS_SECRET_KEY}
  REGION: ap-northeast-2

S3:
  BUCKET:
    NAME: ${S3_BUCKET_NAME}


